version: 0.0
os: linux
files:
  - source: Service/bytesizelinks.service
    destination: /lib/systemd/system
  - source: /app
    destination: /webapps/bytesizelinks
  - source: /html
    destination: /webapps/bytesizelinks/html
  - source: /static
    destination: /webapps/bytesizelinks/static
hooks:
  ApplicationStop:
    - location: Scripts/stop_app.sh
      timeout: 20
  ApplicationStart:
    - location: Scripts/start_app.sh
      timeout: 20
  ValidateService:
    - location: Scripts/validate_app.sh
      timeout: 20