version: 0.2

phases:
  # set go version
  install:
    runtime-versions:
      golang: 1.15

  # download required packages
  pre_build:
    commands:
      - echo Downloading go packages...
      - go get -d -v ./...
  
  # build app, and output to file "app"
  build:
    commands:
      - echo Building app...
      - go build -o app
      - echo Starting unit tests...
      - go test ./pkgs/...

# build artifacts
artifacts:
  files:
    - app
    - appspec.yml
    - html/**/*
    - static/**/*
    - Service/**/*
    - Scripts/**/*
  name: build-$(date +%Y-%m-%d)